
'use server';
/**
 * @fileOverview Extends an initial article, adds more content, and then generates a final "References" section for the combined content.
 *
 * - extendAndFinalizeArticle - A function that extends an article and adds final references.
 * - ExtendAndFinalizeArticleInput - The input type for this function.
 * - ExtendAndFinalizeArticleOutput - The return type for this function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExtendAndFinalizeArticleInputSchema = z.object({
  initialArticleContent: z.string().describe('The initial article content generated by a previous step. It includes in-text links but no final References section.'),
  userTopic: z.string().describe('The original topic for the article.'),
  tone: z.enum(['Academic', 'Blog', 'Creative']).describe('The tone of the article.'),
  format: z.enum(['Plain Text', 'Markdown', 'PDF']).describe('The output format for the article (influences link formatting and References section).'),
});
export type ExtendAndFinalizeArticleInput = z.infer<typeof ExtendAndFinalizeArticleInputSchema>;

const ExtendAndFinalizeArticleOutputSchema = z.object({
  finalFullArticle: z.string().describe('The complete final article, including initial content, extended content, and the comprehensive "References" section at the very end.'),
});
export type ExtendAndFinalizeArticleOutput = z.infer<typeof ExtendAndFinalizeArticleOutputSchema>;

export async function extendAndFinalizeArticle(input: ExtendAndFinalizeArticleInput): Promise<ExtendAndFinalizeArticleOutput> {
  return extendAndFinalizeArticleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'extendAndFinalizeArticlePrompt',
  input: {schema: ExtendAndFinalizeArticleInputSchema},
  output: {schema: ExtendAndFinalizeArticleOutputSchema},
  prompt: `You are an expert research writer and editor. You will perform a multi-step task:
First, you will extend an existing article draft.
Second, you will create a consolidated "References" section for the complete, combined article.

The original topic is: "{{user_topic}}"
The desired tone is: "{{tone}}"
The desired output format is: "{{format}}"

Here is the initial article content you need to extend:
<initial_article_content>
{{{initialArticleContent}}}
</initial_article_content>

**Part 1: Extend Article Content**
1.  Review the 'initialArticleContent' provided above.
2.  Generate approximately 2000-3000 additional words of NEW, relevant content. This new content MUST strictly stay on the original topic: "{{user_topic}}" and maintain the "{{tone}}" tone.
3.  DO NOT repeat information already present in the 'initialArticleContent'. Focus on adding new depth, exploring new sub-topics, or providing further details on aspects briefly mentioned.
4.  Organize your new, additional content logically into sections and subsections using H2 and H3 headings as appropriate for the "{{format}}" output.
5.  After every major new section you add, you MUST include 1-2 real, relevant links from reputable sources (e.g., Wikipedia, Forbes, Scientific American, Harvard.edu, etc.). These links should be directly related to the content of that new section and formatted as clickable links appropriate for the "{{format}}".
6.  Let's call the content generated in this Part 1 "extendedContent".

**Part 2: Combine and Add References Section**
1.  Take the 'initialArticleContent' and append your newly generated 'extendedContent' to it. This forms the "completeArticleBody".
2.  Now, for this "completeArticleBody", create a "References" section that will be placed at the VERY END.
3.  The "References" section must follow these rules:
    a.  **Heading**: Start with a heading. If format is Markdown, use "## References". If format is "Plain Text", use "References:".
    b.  **Extract Links**: Identify and extract ALL unique URLs that are embedded as in-text links throughout the "completeArticleBody" (both initial and extended parts).
    c.  **List URLs**: List each unique URL. Each URL should be on a new line. Format them as clickable links if the "{{format}}" supports it (e.g., in Markdown, use <http://example.com> or [http://example.com](http://example.com)).
    d.  **Annotate Links**: For each URL or group of related URLs, if identifiable from the URL or common knowledge, briefly mention the names of key authors or organizations associated with that source.
    e.  **Mention Key Individuals**: In addition to link annotations, or as part of them, identify and list names of important individuals who have published significant work or are key figures related to the overall article topic "{{userTopic}}". Briefly explain their connection or contribution to the topic. This information might not come directly from the links but from your general knowledge about the topic.

Your final output for 'finalFullArticle' must be a single string containing:
initialArticleContent
(seamlessly followed by)
extendedContent
(seamlessly followed by)
The_Generated_References_Section

Ensure the entire output adheres to the "{{format}}" and "{{tone}}".`,
});

const extendAndFinalizeArticleFlow = ai.defineFlow(
  {
    name: 'extendAndFinalizeArticleFlow',
    inputSchema: ExtendAndFinalizeArticleInputSchema,
    outputSchema: ExtendAndFinalizeArticleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
