
'use server';
/**
 * @fileOverview Extends an initial research article draft (Abstract, Intro, M&M) with Results, Discussion, Conclusion, and a final consolidated References section, aiming for a total of 6000+ words.
 *
 * - extendAndFinalizeArticle - A function that extends an article and adds final references.
 * - ExtendAndFinalizeArticleInput - The input type for this function.
 * - ExtendAndFinalizeArticleOutput - The return type for this function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExtendAndFinalizeArticleInputSchema = z.object({
  initialArticleContent: z.string().describe('The initial article content (Abstract, Introduction, Materials & Methods, preliminary references) generated by a previous step.'),
  userTopic: z.string().describe('The original topic for the research article.'),
  tone: z.enum(['Academic', 'Blog', 'Creative']).describe('The tone of the article (should be Academic).'),
  format: z.enum(['Plain Text', 'Markdown', 'PDF']).describe('The output format for the article.'),
});
export type ExtendAndFinalizeArticleInput = z.infer<typeof ExtendAndFinalizeArticleInputSchema>;

const ExtendAndFinalizeArticleOutputSchema = z.object({
  finalFullArticle: z.string().describe('The complete final research article (Abstract, Introduction, Materials & Methods, Results, Discussion, Conclusion, and the final consolidated References section).'),
});
export type ExtendAndFinalizeArticleOutput = z.infer<typeof ExtendAndFinalizeArticleOutputSchema>;

const promptTemplate = `You are an expert research scientist and academic editor.
The original topic for this research article is: "{{userTopic}}"
The desired tone is: "{{tone}}" (must be Academic)
The desired output format is: "{{format}}"

You are given an initial draft of a research article:
<initial_article_content>
{{{initialArticleContent}}}
</initial_article_content>

Your task is to take this initial draft (which includes Abstract, Introduction, Materials & Methods, and a preliminary reference list) and complete it by adding:
1.  A detailed Results section (approx. 1000-1500 words). This section MUST:
    *   Present hypothetical quantitative findings relevant to the study described in 'initialArticleContent'.
    *   Include descriptions of data that would be suitable for tables (e.g., "Table 1 shows participant demographics... Table 2 presents the diagnostic accuracy metrics..."). Actual table markdown is optional but descriptions of table content are mandatory.
    *   Clearly state the statistical analyses used to derive these hypothetical results.
2.  A comprehensive Discussion section (approx. 1000-1500 words). This section MUST:
    *   Interpret the hypothetical results from the Results section.
    *   Compare these findings with past literature (citing new references as needed).
    *   Discuss implications, limitations of the hypothetical study, and future research directions.
3.  A concise Conclusion section (approx. 200-300 words) summarizing the main findings and their significance.
4.  A final, EXHAUSTIVE "References" section for the ENTIRE combined article. This section will replace any preliminary reference list.

The final "References" section MUST:
    a.  Be titled "## References" (for Markdown/PDF) or "References:" (for Plain Text).
    b.  Include ALL unique references cited throughout the entire article (initial content + new content).
    c.  Ensure a TOTAL of AT LEAST 15 unique, real, and relevant references from the years 2000-2025. Verify relevance to "{{userTopic}}".
    d.  Be formatted strictly in Vancouver style.
    e.  Include PMID or DOI for each reference where available. If not found, state "PMID/DOI not found".
    f.  References must be numbered and ordered chronologically based on their first appearance in the text.
    g.  All in-text citations throughout the entire article (initial and new parts) MUST be in square brackets, e.g., [1], [2,3], [4-6]. Ensure consistency and correct numbering.

Overall Requirements:
-   The total article length (initial content + your extended content) MUST exceed 6000 words.
-   Maintain strict scientific accuracy, originality, and a formal "{{tone}}" (Academic).
-   This must complete an original research article. Reflect updated research insights and ensure technical rigor directly relevant to the study's title and aims based on "{{userTopic}}".
-   Avoid plagiarism and generic AI-generated summaries.
-   Ensure seamless integration of the new sections with the 'initialArticleContent'. All parts (Abstract, Introduction, Materials and Methods, Results, Discussion, Conclusion, References) should form one cohesive document.

Your final output for 'finalFullArticle' must be a single string containing:
The complete Abstract
The complete Introduction
The complete Materials and Methods
The new Results section
The new Discussion section
The new Conclusion section
The final consolidated References section

IMPORTANT: Your entire response MUST be a valid JSON object that conforms to the ExtendAndFinalizeArticleOutputSchema (i.e., {"finalFullArticle": "your complete article string..."}). Do not include any other text, prefixes, explanations, or conversational remarks outside of this JSON object.`;

const systemMessageContent = "You are an AI assistant that strictly follows user instructions. The user will provide a detailed prompt instructing you to generate specific content AND to format your entire response as a single, valid JSON object. Your sole task is to generate this JSON object exactly as described in the user's prompt, conforming to any specified schemas. Do not add any explanatory text, apologies, or conversational remarks before or after the JSON object. Your entire output must be only the JSON object itself.";

async function callGroqAPI(input: ExtendAndFinalizeArticleInput): Promise<ExtendAndFinalizeArticleOutput> {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error("GROQ_API_KEY is not set in environment variables.");
  }

  let userMessageContent = promptTemplate;
  for (const key in input) {
    if (Object.prototype.hasOwnProperty.call(input, key)) {
      const value = (input as any)[key];
      userMessageContent = userMessageContent.replace(new RegExp(`{{{${key}}}}`, 'g'), String(value));
      userMessageContent = userMessageContent.replace(new RegExp(`{{${key}}}`, 'g'), String(value));
    }
  }

  const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${apiKey}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      model: "llama3-70b-8192",
      messages: [
        { role: "system", content: systemMessageContent },
        { role: "user", content: userMessageContent }
      ],
      temperature: 0.7,
      stream: false,
      response_format: { type: "json_object" }
    })
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Groq API request failed with status ${response.status}: ${errorBody}`);
  }

  const data = await response.json();
  const rawOutput = data.choices[0]?.message?.content;

  if (typeof rawOutput !== 'string') {
    throw new Error("Groq API response did not contain expected string content.");
  }

  try {
    const parsedOutput = JSON.parse(rawOutput);
    const validationResult = ExtendAndFinalizeArticleOutputSchema.safeParse(parsedOutput);
    if (!validationResult.success) {
      console.error("Groq output validation error details:", validationResult.error.errors);
      throw new Error(`Groq API output validation failed: ${validationResult.error.message}. Raw: ${rawOutput}`);
    }
    return validationResult.data;
  } catch (e) {
    console.error("Failed to parse Groq API JSON output. Raw output:", rawOutput);
    throw new Error(`Failed to parse or validate Groq API JSON output: ${(e as Error).message}. Raw output: ${rawOutput}`);
  }
}

export async function extendAndFinalizeArticle(input: ExtendAndFinalizeArticleInput): Promise<ExtendAndFinalizeArticleOutput> {
  return extendAndFinalizeArticleFlow(input);
}

const extendAndFinalizeArticleFlow = ai.defineFlow(
  {
    name: 'extendAndFinalizeArticleFlow',
    inputSchema: ExtendAndFinalizeArticleInputSchema,
    outputSchema: ExtendAndFinalizeArticleOutputSchema,
  },
  async (input) => {
     // Force Academic tone for IMRaD structure
    const academicInput = { ...input, tone: 'Academic' as const };
    return callGroqAPI(academicInput);
  }
);
